# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-27 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='annual_dues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_registration_fee', models.IntegerField()),
                ('admission_fee', models.IntegerField()),
                ('annual_paper_fund', models.IntegerField()),
                ('annual_science_fund', models.IntegerField()),
                ('annual_generator_fund', models.IntegerField()),
                ('annual_ice_fund', models.IntegerField()),
                ('class_promotion_fund', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='contact_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent_address', models.TextField()),
                ('present_address', models.TextField()),
                ('father_office_address', models.TextField()),
                ('contact_no', models.IntegerField()),
                ('mother_contact_no', models.IntegerField()),
                ('gurdian_contact_no', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='family_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=150)),
                ('father_name_ur', models.CharField(max_length=150)),
                ('father_cnic', models.CharField(max_length=15)),
                ('gurdian_name', models.CharField(max_length=150)),
                ('gurdian_name_ur', models.CharField(max_length=150)),
                ('gurdian_cnic', models.CharField(max_length=15)),
                ('mother_name', models.CharField(max_length=150)),
                ('mother_name_ur', models.CharField(max_length=150)),
                ('mother_cnic', models.CharField(max_length=15)),
                ('father_education', models.CharField(max_length=50)),
                ('father_profession', models.CharField(max_length=50)),
                ('mother_education', models.CharField(max_length=50)),
                ('mother_profession', models.CharField(max_length=50)),
                ('father_income', models.IntegerField()),
                ('mother_income', models.IntegerField()),
                ('income_household', models.IntegerField()),
                ('no_of_childern', models.IntegerField()),
                ('brother', models.IntegerField()),
                ('sister', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='student_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('student_name_ur', models.CharField(max_length=150)),
                ('student_bform', models.CharField(max_length=15)),
                ('student_dob', models.DateField()),
                ('student_previous_school', models.CharField(max_length=150)),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('student_religion', models.CharField(choices=[('M', 'Muslim'), ('N', 'Non-Muslim')], max_length=1)),
                ('student_cast', models.CharField(max_length=50)),
                ('student_class', models.CharField(max_length=50)),
                ('created_on', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='family_information',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information'),
        ),
        migrations.AddField(
            model_name='contact_information',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information'),
        ),
        migrations.AddField(
            model_name='annual_dues',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student_information'),
        ),
    ]
